name       : sword
version    : 1.8.1
release    : 6
source     :
    - http://crosswire.org/ftpmirror/pub/sword/source/v1.8/sword-1.8.1.tar.gz : ce9aa8f721a737f406115d35ff438bd07c829fce1605f0d6dcdabc4318bc5e93
license    : GPL-2.0-or-later
component  : programming.library
summary    : Library for the support of building bible and bible study software
description: |
    Library for the support of building bible and bible study software
setup      : |
    mkdir build
    cd build
    %cmake -DLIBSWORD_LIBRARY_TYPE=Shared \
           -DSYSCONF_INSTALL_DIR=/etc ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
