name       : sword
version    : 1.7.4
release    : 1
source     :
    - http://crosswire.org/ftpmirror/pub/sword/source/v1.7/sword-1.7.4.tar.gz : 995da8cf5a207c1f09809bf4b9db0bd7d267da5fcdb9d6666c9b313edd9d213d
license    : GPL-2.0
component  : programming
summary    : Library for the support of building bible and bible study software
description: |
    Library for the support of building bible and bible study software
setup      : |
    mkdir build
    cd build
    %cmake -DLIBSWORD_LIBRARY_TYPE=Shared \
           -DSYSCONF_INSTALL_DIR=/etc ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
